### PR TITLE
[Fix #95] Prevent crash of cron component

### LINKED ISSUE #95: Cron component crashes when stopped
The Cron component crashes with a `NullPointerException` when trying to shut down the execution pool. The reason is that the `start` method fails to properly associate the pool with the component.

I'll create a pull request shortly.

### PR DESCRIPTION
**Pull request by sebastianpoeplau**
Additionally, add a test for the component.

### CODE REVIEW

**Comment by prayerslayer** [comment]
Finally someone caring about `cron`, the ugly duck of friboo :grin:

**Comment by prayerslayer** [comment]
:+1:

**Comment by harti2006** [comment]
:+1:

File: test/org/zalando/stups/friboo/system/cron_test.clj [hunk 1]
```diff
@@ -0,0 +1,16 @@
...
+            [overtone.at-at :as at]))
+
+(def-cron-component TestCron [state]
+  (at/at (at/now) (job deliver state 42) pool))
+
+(deftest test-cron-component-lifecycle
+  ;; Here we make sure that the component is started and stopped properly.
+  (let [state (promise)
+        cron-component (map->TestCron {:state state})]
+    (.start cron-component)
```
Comment (dryewo) [inline test/org/zalando/stups/friboo/system/cron_test.clj]: I suspect that this does not test anything, as `cron-component` is immutable and not started in the beginning.
The right way to do it should be something like:

``` clj
(-> (map->TestCron {:state state})
    (component/start)
    (component/stop)
    (component/stop))
```

so that each following call uses the result of the previous one.

**Review by dryewo — CHANGES_REQUESTED** [review]

File: test/org/zalando/stups/friboo/system/cron_test.clj (hunk 1 above)
Comment (sebastianpoeplau) [reply test/org/zalando/stups/friboo/system/cron_test.clj]: Good point, will change it. Actually, the test was enough to reproduce the crash, but you're right in saying that it doesn't actually stop the running component.

**Review by dryewo — APPROVED** [review]

**Comment by dryewo** [comment]
👍

**Comment by sebastianpoeplau** [comment]
👍

**Comment by sebastianpoeplau** [comment]
Too bad, I thought I might be able to give the second approval ;) Is it because I'm not in the Zalando group?

**Comment by sebastianpoeplau** [comment]
Okay, I've been added to the org. Now my approval should count :-)

**Comment by sebastianpoeplau** [comment]
👍

**Comment by sebastianpoeplau** [comment]
I don't seem to be authorized to merge...
